language: java

jdk:
  - oraclejdk8

before_install:
    - chmod +x gradlew
    - curl https://archive.apache.org/dist/lucene/solr/6.2.1/solr-6.2.1.zip -O solr-6.2.1.zip

script: ./gradlew -d build jacocoTestReport

after_success: 
    - ./gradlew -d jacocoRootReport coveralls
    - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
